create table cm_cliente
(
    ID_CM_CLIENTE         int auto_increment comment 'ID PRIMARY KEY DE LA TABLA'
        primary key,
    PRIMER_NOMBRE         varchar(80)                         null,
    SEGUNDO_NOMBRE        varchar(80)                         null,
    PRIMER_APELLIDO       varchar(80)                         null,
    SEGUNDO_APELLIDO      varchar(80)                         null,
    EDAD                  int                                 null,
    ESTADO                char      default 'S'               not null comment 'ESTADO DEL REGISTRO',
    USUARIO_CREACION      varchar(40)                         not null comment 'USUARIO RESPONSBALE DE LA CREACION',
    FECHA_CREACION        timestamp default CURRENT_TIMESTAMP not null comment 'FECHA  DE CREACION DEL REGISTRO',
    USUARIO_ACTUALIZACION varchar(40)                         null comment 'USUARIO RESPONSBALE DE LA CREACION',
    FECHA_ACTUALIZACION   timestamp default CURRENT_TIMESTAMP not null comment 'FECHA  DE CREACION DEL REGISTRO'
)
    comment 'TABLA PARA ALMACENAR INFO DE LOS CLIENTES';

INSERT INTO MEDICENTER.cm_cliente (ID_CM_CLIENTE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EDAD, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (1, 'JUAN', 'JORDAN', 'GARCIA', 'GARCES', 36, 'S', 'MGUALACIO', '2022-01-20 04:22:03', 'MGUALACIO', '2022-01-20 04:22:03');
INSERT INTO MEDICENTER.cm_cliente (ID_CM_CLIENTE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EDAD, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (2, 'RICHARD', 'LEO', 'MORA', 'MOLINA', 26, 'S', 'MGUALACIO', '2022-01-20 04:22:03', 'MGUALACIO', '2022-01-20 04:22:03');
INSERT INTO MEDICENTER.cm_cliente (ID_CM_CLIENTE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EDAD, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (3, 'MARTHA', 'VERONICA', 'GARCIA', 'CEREZO', 46, 'S', 'MGUALACIO', '2022-01-20 04:22:03', 'MGUALACIO', '2022-01-20 04:22:03');
INSERT INTO MEDICENTER.cm_cliente (ID_CM_CLIENTE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EDAD, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (4, 'SAMMY', 'ELENA', 'MERCED', 'YEPEZ', 38, 'S', 'MGUALACIO', '2022-01-20 04:22:03', 'MGUALACIO', '2022-01-20 04:22:03');
INSERT INTO MEDICENTER.cm_cliente (ID_CM_CLIENTE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EDAD, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (5, 'CANDY', 'PENNY', 'STARK', 'ARTEAGA', 66, 'S', 'MGUALACIO', '2022-01-20 04:22:03', 'MGUALACIO', '2022-01-20 04:22:03');
INSERT INTO MEDICENTER.cm_cliente (ID_CM_CLIENTE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EDAD, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (6, 'BETTY', 'ESTER', 'MOLINA', 'ARREAGA', 56, 'S', 'MGUALACIO', '2022-01-20 04:22:03', 'MGUALACIO', '2022-01-20 04:22:03');
INSERT INTO MEDICENTER.cm_cliente (ID_CM_CLIENTE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EDAD, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (7, 'JOEL', 'CRISS', 'GOMEZ', 'SUAREZ', 32, 'S', 'MGUALACIO', '2022-01-20 04:22:03', 'MGUALACIO', '2022-01-20 04:22:03');
INSERT INTO MEDICENTER.cm_cliente (ID_CM_CLIENTE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EDAD, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (8, 'FERNANDO', 'JORDAN', 'DIAZ', 'VERA', 30, 'S', 'MGUALACIO', '2022-01-20 04:22:03', 'MGUALACIO', '2022-01-20 04:22:03');
INSERT INTO MEDICENTER.cm_cliente (ID_CM_CLIENTE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EDAD, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (9, 'BYRON', 'FERNANDO', 'MIRANDA', 'MERCED', 56, 'S', 'MGUALACIO', '2022-01-20 04:22:03', 'MGUALACIO', '2022-01-20 04:22:03');
INSERT INTO MEDICENTER.cm_cliente (ID_CM_CLIENTE, PRIMER_NOMBRE, SEGUNDO_NOMBRE, PRIMER_APELLIDO, SEGUNDO_APELLIDO, EDAD, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (10, 'LUISA', 'BELEN', 'VERA', 'LOPEZ', 36, 'S', 'MGUALACIO', '2022-01-20 04:22:03', 'MGUALACIO', '2022-01-20 04:22:03');
