create table cm_cita
(
    ID_CM_CITA             int auto_increment comment 'ID PRIMARY KEY DE LA TABLA'
        primary key,
    ID_CM_TIPO_PAGO        int                                 not null,
    ID_CM_EMPLEADO         int                                 not null,
    ID_TIPO_ESPECIALIDADES int                                 not null,
    ID_CM_LOCALES          int                                 not null,
    ID_CM_CLIENTE          int                                 not null,
    FECHA_CITA             timestamp                           null,
    DESCRIPCION_CITA       varchar(80)                         null,
    ESTADO                 char      default 'S'               not null comment 'ESTADO DEL REGISTRO',
    USUARIO_CREACION       varchar(40)                         not null comment 'USUARIO RESPONSBALE DE LA CREACION',
    FECHA_CREACION         timestamp default CURRENT_TIMESTAMP not null comment 'FECHA  DE CREACION DEL REGISTRO',
    USUARIO_ACTUALIZACION  varchar(40)                         null comment 'USUARIO RESPONSBALE DE LA CREACION',
    FECHA_ACTUALIZACION    timestamp default CURRENT_TIMESTAMP not null comment 'FECHA  DE CREACION DEL REGISTRO',
    constraint FK_CIT_CLIENTE
        foreign key (ID_CM_CLIENTE) references cm_cliente (ID_CM_CLIENTE),
    constraint FK_CIT_EMPLEADO
        foreign key (ID_CM_EMPLEADO) references cm_empleado (ID_CM_EMPLEADO),
    constraint FK_CIT_LOCALES
        foreign key (ID_CM_LOCALES) references cm_locales (ID_CM_LOCALES),
    constraint FK_CIT_T_ESPECIALIDADES
        foreign key (ID_TIPO_ESPECIALIDADES) references cm_tipo_especialidades (ID_TIPO_ESPECIALIDADES),
    constraint FK_CIT_T_PAGO
        foreign key (ID_CM_TIPO_PAGO) references cm_tipo_pago (ID_CM_TIPO_PAGO)
)
    comment 'TABLA PARA ALMACENAR INFO DE LAS CITAS';

INSERT INTO MEDICENTER.cm_cita (ID_CM_CITA, ID_CM_TIPO_PAGO, ID_CM_EMPLEADO, ID_TIPO_ESPECIALIDADES, ID_CM_LOCALES, ID_CM_CLIENTE, FECHA_CITA, DESCRIPCION_CITA, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (1, 1, 1, 1, 1, 1, '2022-01-20 04:37:40', 'POR COVID 19', 'S', 'MGUALACIO', '2022-01-20 04:37:40', 'MGUALACIO', '2022-01-20 04:37:40');
INSERT INTO MEDICENTER.cm_cita (ID_CM_CITA, ID_CM_TIPO_PAGO, ID_CM_EMPLEADO, ID_TIPO_ESPECIALIDADES, ID_CM_LOCALES, ID_CM_CLIENTE, FECHA_CITA, DESCRIPCION_CITA, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (2, 2, 2, 2, 2, 2, '2022-01-20 04:37:40', 'POR COVID 19', 'S', 'MGUALACIO', '2022-01-20 04:37:40', 'MGUALACIO', '2022-01-20 04:37:40');
INSERT INTO MEDICENTER.cm_cita (ID_CM_CITA, ID_CM_TIPO_PAGO, ID_CM_EMPLEADO, ID_TIPO_ESPECIALIDADES, ID_CM_LOCALES, ID_CM_CLIENTE, FECHA_CITA, DESCRIPCION_CITA, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (3, 3, 3, 3, 3, 3, '2022-01-20 04:37:40', 'POR COVID 19', 'S', 'MGUALACIO', '2022-01-20 04:37:40', 'MGUALACIO', '2022-01-20 04:37:40');
INSERT INTO MEDICENTER.cm_cita (ID_CM_CITA, ID_CM_TIPO_PAGO, ID_CM_EMPLEADO, ID_TIPO_ESPECIALIDADES, ID_CM_LOCALES, ID_CM_CLIENTE, FECHA_CITA, DESCRIPCION_CITA, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (4, 4, 4, 4, 4, 4, '2022-01-20 04:37:40', 'POR COVID 19', 'S', 'MGUALACIO', '2022-01-20 04:37:40', 'MGUALACIO', '2022-01-20 04:37:40');
INSERT INTO MEDICENTER.cm_cita (ID_CM_CITA, ID_CM_TIPO_PAGO, ID_CM_EMPLEADO, ID_TIPO_ESPECIALIDADES, ID_CM_LOCALES, ID_CM_CLIENTE, FECHA_CITA, DESCRIPCION_CITA, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (5, 5, 5, 5, 5, 5, '2022-01-20 04:37:40', 'POR COVID 19', 'S', 'MGUALACIO', '2022-01-20 04:37:40', 'MGUALACIO', '2022-01-20 04:37:40');
INSERT INTO MEDICENTER.cm_cita (ID_CM_CITA, ID_CM_TIPO_PAGO, ID_CM_EMPLEADO, ID_TIPO_ESPECIALIDADES, ID_CM_LOCALES, ID_CM_CLIENTE, FECHA_CITA, DESCRIPCION_CITA, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (6, 6, 6, 6, 6, 6, '2022-01-20 04:37:40', 'POR COVID 19', 'S', 'MGUALACIO', '2022-01-20 04:37:40', 'MGUALACIO', '2022-01-20 04:37:40');
INSERT INTO MEDICENTER.cm_cita (ID_CM_CITA, ID_CM_TIPO_PAGO, ID_CM_EMPLEADO, ID_TIPO_ESPECIALIDADES, ID_CM_LOCALES, ID_CM_CLIENTE, FECHA_CITA, DESCRIPCION_CITA, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (7, 7, 7, 7, 7, 7, '2022-01-20 04:37:40', 'POR COVID 19', 'S', 'MGUALACIO', '2022-01-20 04:37:40', 'MGUALACIO', '2022-01-20 04:37:40');
INSERT INTO MEDICENTER.cm_cita (ID_CM_CITA, ID_CM_TIPO_PAGO, ID_CM_EMPLEADO, ID_TIPO_ESPECIALIDADES, ID_CM_LOCALES, ID_CM_CLIENTE, FECHA_CITA, DESCRIPCION_CITA, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (8, 8, 8, 8, 8, 8, '2022-01-20 04:37:40', 'POR COVID 19', 'S', 'MGUALACIO', '2022-01-20 04:37:40', 'MGUALACIO', '2022-01-20 04:37:40');
INSERT INTO MEDICENTER.cm_cita (ID_CM_CITA, ID_CM_TIPO_PAGO, ID_CM_EMPLEADO, ID_TIPO_ESPECIALIDADES, ID_CM_LOCALES, ID_CM_CLIENTE, FECHA_CITA, DESCRIPCION_CITA, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (9, 9, 9, 9, 9, 9, '2022-01-20 04:37:40', 'POR COVID 19', 'S', 'MGUALACIO', '2022-01-20 04:37:40', 'MGUALACIO', '2022-01-20 04:37:40');
INSERT INTO MEDICENTER.cm_cita (ID_CM_CITA, ID_CM_TIPO_PAGO, ID_CM_EMPLEADO, ID_TIPO_ESPECIALIDADES, ID_CM_LOCALES, ID_CM_CLIENTE, FECHA_CITA, DESCRIPCION_CITA, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (10, 10, 10, 10, 10, 10, '2022-01-20 04:37:40', 'POR COVID 19', 'S', 'MGUALACIO', '2022-01-20 04:37:40', 'MGUALACIO', '2022-01-20 04:37:40');
