create table cm_cargo
(
    ID_CM_CARGO           int auto_increment comment 'ID PRIMARY KEY DE LA TABLA'
        primary key,
    CODIGO_CARGO          char(3)                             null,
    DESCRIPCION_CARGO     varchar(80)                         null,
    ESTADO                char      default 'S'               not null comment 'ESTADO DEL REGISTRO',
    USUARIO_CREACION      varchar(40)                         not null comment 'USUARIO RESPONSBALE DE LA CREACION',
    FECHA_CREACION        timestamp default CURRENT_TIMESTAMP not null comment 'FECHA  DE CREACION DEL REGISTRO',
    USUARIO_ACTUALIZACION varchar(40)                         null comment 'USUARIO RESPONSBALE DE LA CREACION',
    FECHA_ACTUALIZACION   timestamp default CURRENT_TIMESTAMP not null comment 'FECHA  DE CREACION DEL REGISTRO'
)
    comment 'TABLA PARA ALMACENAR LOS TIPOS DE CARGOS DISPONIBLES';

INSERT INTO MEDICENTER.cm_cargo (ID_CM_CARGO, CODIGO_CARGO, DESCRIPCION_CARGO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (1, '001', 'ENFERMERO', 'S', 'ALOPEZ', '2022-01-20 04:18:27', 'ALOPEZ', '2022-01-20 04:18:27');
INSERT INTO MEDICENTER.cm_cargo (ID_CM_CARGO, CODIGO_CARGO, DESCRIPCION_CARGO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (2, '002', 'RECEPCIONISTA', 'S', 'ALOPEZ', '2022-01-20 04:18:27', 'ALOPEZ', '2022-01-20 04:18:27');
INSERT INTO MEDICENTER.cm_cargo (ID_CM_CARGO, CODIGO_CARGO, DESCRIPCION_CARGO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (3, '003', 'DOCTOR', 'S', 'ALOPEZ', '2022-01-20 04:18:27', 'ALOPEZ', '2022-01-20 04:18:27');
INSERT INTO MEDICENTER.cm_cargo (ID_CM_CARGO, CODIGO_CARGO, DESCRIPCION_CARGO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (4, '004', 'DOCTOR JUNIOR', 'S', 'ALOPEZ', '2022-01-20 04:18:27', 'ALOPEZ', '2022-01-20 04:18:27');
INSERT INTO MEDICENTER.cm_cargo (ID_CM_CARGO, CODIGO_CARGO, DESCRIPCION_CARGO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (5, '005', 'AUXILIAR DE ENFERMERIA', 'S', 'ALOPEZ', '2022-01-20 04:18:27', 'ALOPEZ', '2022-01-20 04:18:27');
INSERT INTO MEDICENTER.cm_cargo (ID_CM_CARGO, CODIGO_CARGO, DESCRIPCION_CARGO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (6, '006', 'FARMACEUTICO', 'S', 'ALOPEZ', '2022-01-20 04:18:27', 'ALOPEZ', '2022-01-20 04:18:27');
INSERT INTO MEDICENTER.cm_cargo (ID_CM_CARGO, CODIGO_CARGO, DESCRIPCION_CARGO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (7, '007', 'CONSERJE', 'S', 'ALOPEZ', '2022-01-20 04:18:27', 'ALOPEZ', '2022-01-20 04:18:27');
INSERT INTO MEDICENTER.cm_cargo (ID_CM_CARGO, CODIGO_CARGO, DESCRIPCION_CARGO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (8, '008', 'GUARDIA', 'S', 'ALOPEZ', '2022-01-20 04:18:27', 'ALOPEZ', '2022-01-20 04:18:27');
INSERT INTO MEDICENTER.cm_cargo (ID_CM_CARGO, CODIGO_CARGO, DESCRIPCION_CARGO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (9, '009', 'GERENTE', 'S', 'ALOPEZ', '2022-01-20 04:18:27', 'ALOPEZ', '2022-01-20 04:18:27');
INSERT INTO MEDICENTER.cm_cargo (ID_CM_CARGO, CODIGO_CARGO, DESCRIPCION_CARGO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (10, '010', 'SUB GERENTE', 'S', 'ALOPEZ', '2022-01-20 04:18:27', 'ALOPEZ', '2022-01-20 04:18:27');
