create table cm_diagnostico
(
    ID_CM_DIAGNOSTICO       int auto_increment comment 'ID PRIMARY KEY DE LA TABLA'
        primary key,
    ID_CM_CITA              int                                 not null,
    FECHA_DIAGNOSTICO       timestamp                           null,
    DESCRIPCION_DIAGNOSTICO varchar(80)                         null,
    ES_CONTAGIO             char      default 'S'               not null,
    ESTADO                  char      default 'S'               not null comment 'ESTADO DEL REGISTRO',
    USUARIO_CREACION        varchar(40)                         not null comment 'USUARIO RESPONSBALE DE LA CREACION',
    FECHA_CREACION          timestamp default CURRENT_TIMESTAMP not null comment 'FECHA  DE CREACION DEL REGISTRO',
    USUARIO_ACTUALIZACION   varchar(40)                         null comment 'USUARIO RESPONSBALE DE LA CREACION',
    FECHA_ACTUALIZACION     timestamp default CURRENT_TIMESTAMP not null comment 'FECHA  DE CREACION DEL REGISTRO',
    constraint FK_DIAG_CITA
        foreign key (ID_CM_CITA) references cm_cita (ID_CM_CITA)
)
    comment 'TABLA PARA ALMACENAR INFO DE LAS CITAS';

INSERT INTO MEDICENTER.cm_diagnostico (ID_CM_DIAGNOSTICO, ID_CM_CITA, FECHA_DIAGNOSTICO, DESCRIPCION_DIAGNOSTICO, ES_CONTAGIO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (1, 1, '2022-01-20 04:42:35', 'CONTAGIO POR COVID 19', 'S', 'S', 'KGUZMAN', '2022-01-20 04:42:35', 'KGUZMAN', '2022-01-20 04:42:35');
INSERT INTO MEDICENTER.cm_diagnostico (ID_CM_DIAGNOSTICO, ID_CM_CITA, FECHA_DIAGNOSTICO, DESCRIPCION_DIAGNOSTICO, ES_CONTAGIO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (2, 2, '2022-01-20 04:42:35', 'CONTAGIO POR VARIANTE DELTA', 'S', 'S', 'KGUZMAN', '2022-01-20 04:42:35', 'KGUZMAN', '2022-01-20 04:42:35');
INSERT INTO MEDICENTER.cm_diagnostico (ID_CM_DIAGNOSTICO, ID_CM_CITA, FECHA_DIAGNOSTICO, DESCRIPCION_DIAGNOSTICO, ES_CONTAGIO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (3, 3, '2022-01-20 04:42:35', 'CONTAGIO POR OMICRON', 'S', 'S', 'KGUZMAN', '2022-01-20 04:42:35', 'KGUZMAN', '2022-01-20 04:42:35');
INSERT INTO MEDICENTER.cm_diagnostico (ID_CM_DIAGNOSTICO, ID_CM_CITA, FECHA_DIAGNOSTICO, DESCRIPCION_DIAGNOSTICO, ES_CONTAGIO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (4, 4, '2022-01-20 04:42:35', 'RESFRIADO', 'S', 'S', 'KGUZMAN', '2022-01-20 04:42:35', 'KGUZMAN', '2022-01-20 04:42:35');
INSERT INTO MEDICENTER.cm_diagnostico (ID_CM_DIAGNOSTICO, ID_CM_CITA, FECHA_DIAGNOSTICO, DESCRIPCION_DIAGNOSTICO, ES_CONTAGIO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (5, 5, '2022-01-20 04:42:35', 'CINFLUENZA', 'S', 'S', 'KGUZMAN', '2022-01-20 04:42:35', 'KGUZMAN', '2022-01-20 04:42:35');
INSERT INTO MEDICENTER.cm_diagnostico (ID_CM_DIAGNOSTICO, ID_CM_CITA, FECHA_DIAGNOSTICO, DESCRIPCION_DIAGNOSTICO, ES_CONTAGIO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (6, 6, '2022-01-20 04:42:35', 'CONTAGIO POR COVID 19', 'S', 'S', 'KGUZMAN', '2022-01-20 04:42:35', 'KGUZMAN', '2022-01-20 04:42:35');
INSERT INTO MEDICENTER.cm_diagnostico (ID_CM_DIAGNOSTICO, ID_CM_CITA, FECHA_DIAGNOSTICO, DESCRIPCION_DIAGNOSTICO, ES_CONTAGIO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (7, 7, '2022-01-20 04:42:35', 'CONTAGIO POR VARIACION LEVE DE COVID 19', 'S', 'S', 'KGUZMAN', '2022-01-20 04:42:35', 'KGUZMAN', '2022-01-20 04:42:35');
INSERT INTO MEDICENTER.cm_diagnostico (ID_CM_DIAGNOSTICO, ID_CM_CITA, FECHA_DIAGNOSTICO, DESCRIPCION_DIAGNOSTICO, ES_CONTAGIO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (8, 8, '2022-01-20 04:42:35', 'CONTAGIO POR VARIACION ALPHA', 'S', 'S', 'KGUZMAN', '2022-01-20 04:42:35', 'KGUZMAN', '2022-01-20 04:42:35');
INSERT INTO MEDICENTER.cm_diagnostico (ID_CM_DIAGNOSTICO, ID_CM_CITA, FECHA_DIAGNOSTICO, DESCRIPCION_DIAGNOSTICO, ES_CONTAGIO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (9, 9, '2022-01-20 04:42:35', 'CONTAGIO POR COVID VARIACION MU', 'S', 'S', 'KGUZMAN', '2022-01-20 04:42:35', 'KGUZMAN', '2022-01-20 04:42:35');
INSERT INTO MEDICENTER.cm_diagnostico (ID_CM_DIAGNOSTICO, ID_CM_CITA, FECHA_DIAGNOSTICO, DESCRIPCION_DIAGNOSTICO, ES_CONTAGIO, ESTADO, USUARIO_CREACION, FECHA_CREACION, USUARIO_ACTUALIZACION, FECHA_ACTUALIZACION) VALUES (10, 10, '2022-01-20 04:42:35', 'CONTAGIO POR COVID 19', 'S', 'S', 'KGUZMAN', '2022-01-20 04:42:35', 'KGUZMAN', '2022-01-20 04:42:35');
