services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD_ROOT}
      MYSQL_DATABASE: ${DATABASE_NAME}
    networks:
      - app-network
    volumes:
      - ./database:/var/lib/mysql
      - ./datawarehouse/mydb/:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

networks:
  app-network:
    driver: bridge
